Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -20,16 +20,14 @@ jobs:
       - uses: actions/checkout@v2
       - run: |
           git fetch origin develop
-          git branch --all
-          git branch -r origin/develop --contains ${{ github.event.pull_request.head.sha }} 
-          if [ -z "$(git branch -r origin/develop --format="%(refname:short)" --contains ${{ github.event.pull_request.head.sha }} )" ]; then
-              echo "No commits in develop branch" >&2
-              exit 1
-          else 
+          if git branch -r origin/develop --contains ${{ github.event.pull_request.head.sha }}; then
               echo "Commits in develop - Check Passed"
-          fi         
+          else 
+              echo "No commits in develop branch">&2
+              exit 1
+          fi        
         env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}       
 
   enforce-branching-rules:
     name: Ensure proper branching rules
@@ -42,11 +40,13 @@ jobs:
 
       - name: Ensure develop is up-to-date before merging to main
         run: |
-          git fetch origin
-          git checkout develop
-          if [ "$(git rev-parse develop)" != "$(git merge-base develop main)" ]; then
-            echo "Feature branch must be merged into develop before merging to main"
-            exit 1
+          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
+              git fetch origin
+              git checkout develop
+              if [ "$(git rev-parse develop)" != "$(git merge-base develop main)" ]; then
+                  echo "Feature branch must be merged into develop before merging to main"
+                  exit 1
+              fi
           fi
 
   protect-develop:
@@ -61,8 +61,8 @@ jobs:
         run: |
           git fetch origin
           if [ "$(git rev-parse HEAD)" != "$(git rev-parse origin/develop)" ]; then
-            echo "You cannot push directly to develop after rebasing. Please recreate your local develop branch."
-            exit 1
+              echo "You cannot push directly to develop after rebasing. Please recreate your local develop branch."
+              exit 1
           fi   
 
   check-merge:
@@ -78,10 +78,13 @@ jobs:
 
       - name: Ensure develop is up-to-date before merging to main
         run: |
-          git checkout develop
-          if [ "$(git rev-parse develop)" != "$(git merge-base develop main)" ]; then
-            echo "Feature branch must be merged into develop before merging to main"
-            exit 1
+          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
+              git checkout develop
+              git checkout main
+              if [ "$(git rev-parse develop)" != "$(git merge-base develop main)" ]; then
+                  echo "Feature branch must be merged into develop before merging to main"
+                  exit 1
+              fi
           fi
 
   check-black-format:
@@ -111,9 +114,6 @@ jobs:
           else                    
               echo "Py-files in the commit"
               for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
-                  # Skip non-Python files
-                  if [[ "$file" == *.py ]]; then
-                      black --check --diff --line-length=79 "$file" || exit 1
-                  fi
+                  black --check --diff --line-length=79 "$file"
               done    
           fi
